### ISSUE TITLE
No current data with version 1.4.1, 2.1.0 

### ISSUE THREAD

**Issue by franzoni** [SwissCovid/swisscovid-app-android#298]
Similarly to:
https://github.com/DP-3T/dp3t-app-android-ch/issues/100

I have been having the error for about a day, despite definitely internet connected. 
Android miui V12.0.4.0.QFDMIXM is my operative system. I have another covid tracking app, though I've kept it off for months with no problems.

Thanks for your help

**Comment by franzoni** [comment]
![IMG-20210407-WA0008](https://user-images.githubusercontent.com/4729828/113921335-2ab96f00-97e6-11eb-8f6d-421e0a97f841.jpg)

**Comment by franzoni** [comment]
I've rebooted for a minor update ( the operative system is still the same miui V12.0.4.0.QFDMIXM) and now the error is gone.

**Comment by mlacayoemery** [comment]
Same issue on a Pixel 3 XL running stock Android 11 build RQ2A.210405.005. Android indicates app has no permissions requested, which is surprising.

**Comment by simonroesch** [comment]
With SwissCovid 2.0 these errors should no longer appear. Please open a new issue if you still see unexpected errors on SwissCovid 2.0.
