### ISSUE TITLE
app sys "Keine aktuellen Daten"

### ISSUE THREAD

**Issue by simuuh** [SwissCovid/swisscovid-app-android#304]
The app reminds tells me: 

> Seit einiger Zeit konnten die Meldungen nicht synchronisiert werden. Stellen Sie sicher, dass Ihr Mobiltelefon mit dem Internet verbunden ist. (LOST) | Erneut versuchen | RTSENLOST

But under _Settings -> Google -> COVID-19-BENACHRICHTIGUNGEN -> Mögliche Begegnungen_ are entries on 14.04, 13.04, 12.04 listed.

![Screenshot_20210414-090756_SwissCovid](https://user-images.githubusercontent.com/19995928/114670024-dbea6880-9d02-11eb-9822-9a765721d17f.jpg)
![Screenshot_20210414-090742_Google Play services](https://user-images.githubusercontent.com/19995928/114670034-dee55900-9d02-11eb-8020-4f364d051abc.jpg)

what i did before create this issue
- device restarted
- closed the app and opened it again

**Comment by kohlerdominik** [comment]
I can confirm this issue on my OnePlus Nord.

**Comment by kohlerdominik** [comment]
> 
> 
> I can confirm this issue on my OnePlus Nord.

Update: just now works again.

**Comment by denysvitali** [comment]
Same here, OnePlus 8 Pro

**Comment by MarioPerini** [comment]
Same issue here since today, last successfull sync: 04.05.2021 10:26:08

CAT S62 Pro (Android 10) all Apps and System up-to-date
Version 1.4.1, 2.1.0
App restart -> no success
Device reboot -> no success

**Comment by aaronmeder** [comment]
I've got a similar error `RTSENCANCEL` on my OnePlus 5T for the last few weeks. Battery Optimisation is disabled for the SwissCovid App. It worked well a few months back.

**Comment by simonroesch** [comment]
With SwissCovid 2.0 these errors should no longer appear. Please open a new issue if you still see unexpected errors on SwissCovid 2.0.

**Comment by denysvitali** [comment]
@simonroesch Do you mind sharing what was the issue and what commit solved it?

**Comment by simonroesch** [comment]
These issues were part of the DP3T SDK. First we solved the "LOST" error message with https://github.com/DP-3T/dp3t-sdk-android/pull/239 and later we fixed the "RTSENCANCEL" error with https://github.com/DP-3T/dp3t-sdk-android/pull/254
