### ISSUE TITLE
keine aktuellen Daten (RTSENCANCEL) 1.5.0/2.2.0

### ISSUE THREAD

**Issue by judos** [SwissCovid/swisscovid-app-android#393]
Siehe Screenshots.
Knopf "Erneut versuchen" bringt nichts. Beim anklicken erscheint lade-spinner und dieser bleibt dann solange bis ich irgendetwas anderes anwähle.
Swisscovid App 1.5.0/2.2.0
Samsung Galaxy S7

![Screenshot_20210625-122919_SwissCovid](https://user-images.githubusercontent.com/5525810/123412358-cc648700-d5b1-11eb-8735-fcf57abb67a2.jpg)
![Screenshot_20210625-122912_SwissCovid](https://user-images.githubusercontent.com/5525810/123412362-ccfd1d80-d5b1-11eb-9b77-f24fc5bb408e.jpg)

**Comment by neonknight** [comment]
Hier dasselbe (Nokia 3.1 mit Android 10, SwissCovid Version 2.0.0, 2.3.0).

Interessanterweise steht unter "Encounters" -> "Latest successful synchronisation" ein Zeitstempel von heute.

**Comment by 14yannick** [comment]
bei mir auch Pixel 4a 5g Android 11. SwissCovid Version 2.0.0, 2.3.0.

**Comment by simonroesch** [comment]
Mit Version 2.0.1 der SwissCovid App sollte dieses Problem nicht mehr auftreten.

**Comment by CDRO** [comment]
Der Fehler tritt unter Android auf Version 2.0.1, 2.3.1 weiterhin/wieder? auf.

Nokia 8.3 5G
